### ISSUE TITLE
Learnset Glitch

### ISSUE THREAD

**Issue by Zfraz1** [haven1433/HexManiacAdvance#105] opened 2023-01-04 04:25 UTC
Hi there, just started creating a FR hack, no prior coding experience.

I edited almost every trainer and updated a few pokemon in PGE, and updated some encounters in advance map, all of which transferred to HMA successfully. 

In HMA, I made it so the top-most employee on the second floor of the celadon mart sold all 50 tms, instead of just the original 5. I'm guessing this overloaded some memory or something, because now every single pokemon learnset looks like this:
![Screenshot (16)](https://user-images.githubusercontent.com/121919061/210484291-73939e10-5f9a-4538-8526-eccbd22a001c.png)

Any way to fix this? I could go through and edit every learnset individually, but... yikes.

I also expanded the available moves and added 4 new moves, maybe that has something to do with it.

Thanks!

**Comment by haven1433** [comment] 2023-01-05 23:05
We talked about this issue on Discord and decided it was a toml configuration issue, not a bug in HMA. Closing the issue.

**Closed by haven1433** 2023-01-05 23:05 UTC
